/**
{
	"api":1,
	"name":"Emoji to Shortcode",
	"description":"Converts emoji to shortcodes (😀 → :smile:)",
	"author":"danrodz",
	"icon":"bolt",
	"tags":"emoji,shortcode,encode"
}
**/

function main(input) {
	const emojiMap = {
		'😀': ':grinning:',
		'😃': ':smile:',
		'😄': ':smiley:',
		'😁': ':grin:',
		'😆': ':laughing:',
		'😅': ':sweat_smile:',
		'🤣': ':rofl:',
		'😂': ':joy:',
		'🙂': ':slightly_smiling_face:',
		'🙃': ':upside_down_face:',
		'😉': ':wink:',
		'😊': ':blush:',
		'😇': ':innocent:',
		'🥰': ':smiling_face_with_three_hearts:',
		'😍': ':heart_eyes:',
		'🤩': ':star_struck:',
		'😘': ':kissing_heart:',
		'😗': ':kissing:',
		'😚': ':kissing_closed_eyes:',
		'😙': ':kissing_smiling_eyes:',
		'🥲': ':smiling_face_with_tear:',
		'😋': ':yum:',
		'😛': ':stuck_out_tongue:',
		'😜': ':stuck_out_tongue_winking_eye:',
		'🤪': ':zany_face:',
		'😝': ':stuck_out_tongue_closed_eyes:',
		'🤑': ':money_mouth_face:',
		'🤗': ':hugs:',
		'🤭': ':hand_over_mouth:',
		'🤫': ':shushing_face:',
		'🤔': ':thinking:',
		'🤐': ':zipper_mouth_face:',
		'🤨': ':raised_eyebrow:',
		'😐': ':neutral_face:',
		'😑': ':expressionless:',
		'😶': ':no_mouth:',
		'😏': ':smirk:',
		'😒': ':unamused:',
		'🙄': ':roll_eyes:',
		'😬': ':grimacing:',
		'🤥': ':lying_face:',
		'😌': ':relieved:',
		'😔': ':pensive:',
		'😪': ':sleepy:',
		'🤤': ':drooling_face:',
		'😴': ':sleeping:',
		'😷': ':mask:',
		'🤒': ':face_with_thermometer:',
		'🤕': ':face_with_head_bandage:',
		'🤢': ':nauseated_face:',
		'🤮': ':vomiting_face:',
		'🤧': ':sneezing_face:',
		'🥵': ':hot_face:',
		'🥶': ':cold_face:',
		'😵': ':dizzy_face:',
		'🤯': ':exploding_head:',
		'😎': ':sunglasses:',
		'🤓': ':nerd_face:',
		'🧐': ':monocle_face:',
		'😕': ':confused:',
		'😟': ':worried:',
		'🙁': ':slightly_frowning_face:',
		'😮': ':open_mouth:',
		'😯': ':hushed:',
		'😲': ':astonished:',
		'😳': ':flushed:',
		'🥺': ':pleading_face:',
		'😦': ':frowning:',
		'😧': ':anguished:',
		'😨': ':fearful:',
		'😰': ':cold_sweat:',
		'😥': ':disappointed_relieved:',
		'😢': ':cry:',
		'😭': ':sob:',
		'😱': ':scream:',
		'😖': ':confounded:',
		'😣': ':persevere:',
		'😞': ':disappointed:',
		'😓': ':sweat:',
		'😩': ':weary:',
		'😫': ':tired_face:',
		'🥱': ':yawning_face:',
		'😤': ':triumph:',
		'😡': ':rage:',
		'😠': ':angry:',
		'🤬': ':cursing_face:',
		'😈': ':smiling_imp:',
		'👿': ':imp:',
		'💀': ':skull:',
		'☠️': ':skull_and_crossbones:',
		'💩': ':poop:',
		'🤡': ':clown_face:',
		'👹': ':japanese_ogre:',
		'👺': ':japanese_goblin:',
		'👻': ':ghost:',
		'👽': ':alien:',
		'👾': ':space_invader:',
		'🤖': ':robot:',
		'🎃': ':jack_o_lantern:',
		'😺': ':smiley_cat:',
		'😸': ':smile_cat:',
		'😹': ':joy_cat:',
		'😻': ':heart_eyes_cat:',
		'😼': ':smirk_cat:',
		'😽': ':kissing_cat:',
		'🙀': ':scream_cat:',
		'😿': ':crying_cat_face:',
		'😾': ':pouting_cat:',
		'❤️': ':heart:',
		'🧡': ':orange_heart:',
		'💛': ':yellow_heart:',
		'💚': ':green_heart:',
		'💙': ':blue_heart:',
		'💜': ':purple_heart:',
		'🖤': ':black_heart:',
		'🤍': ':white_heart:',
		'🤎': ':brown_heart:',
		'💔': ':broken_heart:',
		'❣️': ':heavy_heart_exclamation:',
		'💕': ':two_hearts:',
		'💞': ':revolving_hearts:',
		'💓': ':heartbeat:',
		'💗': ':heartpulse:',
		'💖': ':sparkling_heart:',
		'💘': ':cupid:',
		'💝': ':gift_heart:',
		'💟': ':heart_decoration:',
		'☮️': ':peace_symbol:',
		'✝️': ':latin_cross:',
		'☪️': ':star_and_crescent:',
		'🕉️': ':om:',
		'☸️': ':wheel_of_dharma:',
		'✡️': ':star_of_david:',
		'🔯': ':six_pointed_star:',
		'🕎': ':menorah:',
		'☯️': ':yin_yang:',
		'☦️': ':orthodox_cross:',
		'🛐': ':place_of_worship:',
		'⛎': ':ophiuchus:',
		'♈': ':aries:',
		'♉': ':taurus:',
		'♊': ':gemini:',
		'♋': ':cancer:',
		'♌': ':leo:',
		'♍': ':virgo:',
		'♎': ':libra:',
		'♏': ':scorpius:',
		'♐': ':sagittarius:',
		'♑': ':capricorn:',
		'♒': ':aquarius:',
		'♓': ':pisces:',
		'👍': ':thumbsup:',
		'👎': ':thumbsdown:',
		'👏': ':clap:',
		'🙌': ':raised_hands:',
		'👐': ':open_hands:',
		'🤝': ':handshake:',
		'🙏': ':pray:',
		'✌️': ':v:',
		'🤞': ':crossed_fingers:',
		'🤟': ':love_you_gesture:',
		'🤘': ':metal:',
		'🤙': ':call_me_hand:',
		'👌': ':ok_hand:',
		'🤏': ':pinching_hand:',
		'👈': ':point_left:',
		'👉': ':point_right:',
		'👆': ':point_up_2:',
		'👇': ':point_down:',
		'☝️': ':point_up:',
		'✋': ':raised_hand:',
		'🤚': ':raised_back_of_hand:',
		'🖐️': ':raised_hand_with_fingers_splayed:',
		'🖖': ':vulcan_salute:',
		'👋': ':wave:',
		'🤛': ':left_facing_fist:',
		'🤜': ':right_facing_fist:',
		'✊': ':fist:',
		'👊': ':facepunch:',
		'🤲': ':palms_up_together:',
		'💪': ':muscle:',
		'🦾': ':mechanical_arm:',
		'🦿': ':mechanical_leg:',
		'🦵': ':leg:',
		'🦶': ':foot:',
		'👂': ':ear:',
		'🦻': ':ear_with_hearing_aid:',
		'👃': ':nose:',
		'🧠': ':brain:',
		'🦷': ':tooth:',
		'🦴': ':bone:',
		'👀': ':eyes:',
		'👁️': ':eye:',
		'👅': ':tongue:',
		'👄': ':lips:',
		'🔥': ':fire:',
		'💯': ':100:',
		'✨': ':sparkles:',
		'⭐': ':star:',
		'🌟': ':star2:',
		'💫': ':dizzy:',
		'🎉': ':tada:',
		'🎊': ':confetti_ball:',
		'🎈': ':balloon:',
		'🎁': ':gift:',
		'🏆': ':trophy:',
		'🥇': ':first_place_medal:',
		'🥈': ':second_place_medal:',
		'🥉': ':third_place_medal:',
		'⚽': ':soccer:',
		'⚾': ':baseball:',
		'🥎': ':softball:',
		'🏀': ':basketball:',
		'🏐': ':volleyball:',
		'🏈': ':football:',
		'🏉': ':rugby_football:',
		'🎾': ':tennis:',
		'🥏': ':flying_disc:',
		'🎳': ':bowling:',
		'🏏': ':cricket:',
		'🏑': ':field_hockey:',
		'🏒': ':ice_hockey:',
		'🥍': ':lacrosse:',
		'🏓': ':ping_pong:',
		'🏸': ':badminton:',
		'🥊': ':boxing_glove:',
		'🥋': ':martial_arts_uniform:',
		'🥅': ':goal_net:',
		'⛳': ':golf:',
		'⛸️': ':ice_skate:',
		'🎣': ':fishing_pole_and_fish:',
		'🤿': ':diving_mask:',
		'🎿': ':ski:',
		'🛷': ':sled:',
		'🥌': ':curling_stone:',
		'🎯': ':dart:',
		'🪀': ':yo_yo:',
		'🪁': ':kite:',
		'🎱': ':8ball:',
		'🔮': ':crystal_ball:',
		'🪄': ':magic_wand:',
		'🎮': ':video_game:',
		'🕹️': ':joystick:',
		'🎰': ':slot_machine:',
		'🎲': ':game_die:',
		'🧩': ':jigsaw:',
		'🧸': ':teddy_bear:',
		'🪅': ':pinata:',
		'🪆': ':nesting_dolls:',
		'♠️': ':spades:',
		'♥️': ':hearts:',
		'♦️': ':diamonds:',
		'♣️': ':clubs:',
		'♟️': ':chess_pawn:',
		'🃏': ':black_joker:',
		'🀄': ':mahjong:',
		'🎴': ':flower_playing_cards:',
		'🎭': ':performing_arts:',
		'🖼️': ':framed_picture:',
		'🎨': ':art:',
		'🧵': ':thread:',
		'🪡': ':sewing_needle:',
		'🧶': ':yarn:'
	};

	try {
		let result = input.text;

		// Sort by emoji length (longer first) to handle multi-character emojis
		const sortedEmojis = Object.keys(emojiMap).sort((a, b) => b.length - a.length);

		for (const emoji of sortedEmojis) {
			result = result.split(emoji).join(emojiMap[emoji]);
		}

		input.text = result;
	} catch (error) {
		input.postError('Failed to convert emoji to shortcodes: ' + error.message);
	}
}
